language: elixir
elixir:
  - 1.6.5
otp_release:
  - 20.0

dist: trusty
sudo: false
addons:
  postgresql: '9.6'
services:
  - postgresql

install:
  - mix local.rebar --force
  - mix local.hex --force
script: ./script/cibuild
